apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: dadn
spec:
  selector:
    app: server
  ports:
    - port: 4000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: quangtuan9237/dadn-server
          env:
            - name: PORT
              value: '4000'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: dadn-secret
                  key: JWT_KEY
            - name: ADAFRUIT_KEY
              valueFrom:
                secretKeyRef:
                  name: dadn-secret
                  key: ADAFRUIT_KEY
            - name: ADAFRUIT_USER
              valueFrom:
                secretKeyRef:
                  name: dadn-secret
                  key: ADAFRUIT_USER
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: dadn-secret
                  key: MONGO_URI
